try:
    print(5/0)
except:
    print("ocurrió un error")
finally:
    print("terminó de ejecutarse nuestro código")